name: SimplyWhitelist
version: 1.0.0
main: io.ejpo.simplywhitelist.PluginMain
description: Runs a small discord bot that allows users to whitelist their Minecraft Accounts through Discord
author: Ethan O'Donnell
website: https://ejpo.io
api-version: '1.20'